apiVersion: apps/v1
kind: Deployment
metadata:
  name: howtos-webapp
  namespace: howtos-prod
  labels:
    app: howtos-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: howtos-webapp
  template:
    metadata:
      labels:
        app: howtos-webapp
    spec:
      containers:
        - image: registry.digitalocean.com/tiveritz/howtos-webapps:{{version}}
          name: howtos-webapp
          env:
            - name: VERSION
              value: "{{version}}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: secret-key
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: debug
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: allowed-hosts
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: csrf_trusted_origins
            - name: SECURE_SSL_REDIRECT
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: secure-ssl-redirect
            - name: REQUESTS_SSL_VERIFICATION
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: requests-ssl-verification
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: db-pass
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: db-port
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: api-url
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: aws-s3-access-key-id
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: howtos-webapp-env
                  key: aws-s3-secret-access-key
          ports:
            - containerPort: 8080
              name: gunicorn
