apiVersion: apps/v1
kind: Deployment
metadata:
  name: howtos-webapp
  namespace: howtos-prod
  labels:
    app: howtos-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: howtos-webapp
  template:
    metadata:
      labels:
        app: howtos-webapp
    spec:
      containers:
        - image: registry.digitalocean.com/tiveritz/howto-webapp:{{version}}
          name: howtos-webapp
          ports:
            - containerPort: 8080
              name: gunicorn
