name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
    - name: Tag Image 
      run:
        docker tag tiveritz/howto-webapp \
        registry.digitalocean.com/tiveritz/howto-webapp:${{github.event.inputs.version }}
    - name: Push Image to DO Container Registry 
      run: docker push registry.digitalocean.com/tiveritz/howto-webapp:${{ github.event.inputs.version }}
